name: Docs

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7

      - uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Setup OPA
        uses: open-policy-agent/setup-opa@v2
        with:
          version: 1.2.0

      - name: Download external policy bundles
        run: ./scripts/download-external-bundles.sh

      - name: Generate policy annotation objects using OPA
        run: ./scripts/annotations-generate.sh

      - name: Generate policy bundle metadata object from annotations
        run: python ./scripts/generate_bundle_info.py

      - name: Generate policy documentation from metadata object
        run: python ./scripts/docs_policy_bundles.py

      - name: Prepare dependencies
        run: npm ci --cache .npm --prefer-offline

      - name: Generate documentation
        run: ./hack/docs-generate.sh

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/site/

  deploy:
    needs: generate
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
